feature:
  - changed-files:
    - any-glob-to-any-file:
      - "app.py"
      - "templates/**"
bug:
  - changed-files:
    - any-glob-to-any-file:
      - "tests/**"
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - "static/**"
infra:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/**"
      - "requirements.txt"
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "README.md"