[pytest]
testpaths = test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers --disable-warnings
markers =
    auth: testes de autenticação
    validation: testes de validação
    integration: testes de integração
    slow: testes lentos
    unit: testes unitários
