"""Adicionar campos reset_token e reset_expires na tabela user

Revision ID: 3ddcfea462c8
Revises: 18ae1fa7c1c0
Create Date: 2025-11-20 21:23:57.040977

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3ddcfea462c8"
down_revision: Union[str, Sequence[str], None] = "18ae1fa7c1c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("reset_token", sa.String(length=100), nullable=True)
    )
    op.add_column("user", sa.Column("reset_expires", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "reset_expires")
    op.drop_column("user", "reset_token")
    # ### end Alembic commands ###
