"""Add user preferences columns

Revision ID: 741e1f18573e
Revises: 876ce23e2db8
Create Date: 2025-11-20 23:54:21.285602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "741e1f18573e"
down_revision: Union[str, Sequence[str], None] = "876ce23e2db8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("notificacoes_email", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("notificacoes_push", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("lembretes", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("idioma", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "idioma")
    op.drop_column("user", "lembretes")
    op.drop_column("user", "notificacoes_push")
    op.drop_column("user", "notificacoes_email")
    op.create_table(
        "Livros",
        sa.Column(
            "ID_livro",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Titulo", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "Autor_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("ISBN", mysql.VARCHAR(length=13), nullable=False),
        sa.Column(
            "Ano_publicacao",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Genero_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Editora_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Quantidade_disponivel",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Resumo", mysql.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["Autor_id"], ["Autores.ID_autor"], name="Livros_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["Editora_id"], ["Editoras.ID_editora"], name="Livros_ibfk_3"
        ),
        sa.ForeignKeyConstraint(
            ["Genero_id"], ["Generos.ID_genero"], name="Livros_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("ID_livro"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Autores",
        sa.Column(
            "ID_autor",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Nome_autor", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("Nacionalidade", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("Data_nascimento", sa.DATE(), nullable=True),
        sa.Column("Biografia", mysql.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("ID_autor"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Editoras",
        sa.Column(
            "ID_editora",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Nome_editora", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("Endereco_editora", mysql.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("ID_editora"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Usuarios",
        sa.Column(
            "ID_usuario",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Nome_usuario", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("Email", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("Numero_telefone", mysql.VARCHAR(length=15), nullable=True),
        sa.Column("Data_inscricao", sa.DATE(), nullable=True),
        sa.Column("Multa_atual", mysql.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("Senha", mysql.VARCHAR(length=300), nullable=True),
        sa.PrimaryKeyConstraint("ID_usuario"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Generos",
        sa.Column(
            "ID_genero",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("Nome_genero", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("ID_genero"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Emprestimos",
        sa.Column(
            "ID_emprestimo",
            mysql.INTEGER(display_width=11),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "Usuario_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "Livro_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Data_emprestimo", sa.DATE(), nullable=True),
        sa.Column("Data_devolucao_prevista", sa.DATE(), nullable=True),
        sa.Column("Data_devolucao_real", sa.DATE(), nullable=True),
        sa.Column(
            "Status_emprestimo",
            mysql.ENUM("pendente", "devolvido", "atrasado"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["Livro_id"], ["Livros.ID_livro"], name=op.f("Emprestimos_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["Usuario_id"], ["Usuarios.ID_usuario"], name=op.f("Emprestimos_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("ID_emprestimo"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
